version: "3"
services:
  web:
    build: "./web"
    image: web
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: guestbook
      DB_USER: guestbook
      DB_PASS: password
    depends_on:
      - db
    ports:
      - "80:80"
  
  db:
    build: "./db"
    image: db
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: guestbook
      MYSQL_USER: guestbook
      MYSQL_PASSWORD: password
    volumes:
      - "db_data:/var/lib/mysql"
    ports:
      - "3306:3306"

volumes:
  db_data: 
